services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Zwo3\NewsletterSubscribe\:
    resource: '../Classes/*'

  Zwo3\NewsletterSubscribe\Command\FillsalutationCommand:
    tags:
      - name: 'console.command'
        command: 'newslettersubscribe:fillsalutation'
        description: 'Fill salutation field in tt_address'

  Zwo3\NewsletterSubscribe\Command\FillsubscriptionhashCommand:
    tags:
      - name: 'console.command'
        command: 'newslettersubscribe:fillsubscriptionhash'
        description: 'Fill subscription hash field in tt_address'
